### ISSUE TITLE
Computation of the residual intensity image and an upper bound on p value

### ISSUE THREAD

**Issue by infinitron** [astrostat/LIRA#1]
Hi,

I'm slightly confused about computing the test statistic ξ. I've generated output images from LIRA by comparing an X-ray observation with a baseline model. So, to compute a distribution of ξ for each ROI, should I just take the fraction of counts in the MS component in each image for each ROI? Should I then use such distributions from the simulated and replicated images to obtain a value of c and then compute the upper limits on p? Am I thinking in the right way? And, should I use a kernel density estimate to smooth the distribution of ξ?

Also, I'm not sure how to generate a residual intensity image from the mean posterior. 

Sorry, I'm new to statistics and I'm still trying to understand Stein et al's paper.
I would greatly appreciate any help on this issue.

Thanks,
Karthik

**Comment by vkashyap** [comment]
Hi Karthik,

ξ is the fraction attributable to the extra component, so what you should do is, for each iteration, compute the total signal within the ROI (τ₁) and also compute the baseline intensity times the area of the ROI (τ₀), and compute ξ = τ₁/(τ₁+τ₀).  The set of all ξ from all the iterations makes the observed distribution of ξ.  This observed distribution is then compared to the simulated distributions generated from the null images.  Do not smooth anything, but do define the ROI before you start doing the test.  The method does not allow checking several ROIs to find the "best" one.

The output of the code _is_ the residual intensity.  It is the component required to the fit the data _in addition_ to the baseline component.

Cheers,
Vinay

**Comment by infinitron** [comment]
I see. That makes sense now. Thanks!
